Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,13 +23,14 @@ build-main:
   only:
     - tags
   script:
-    - if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
-    - TAG_CLEANED=$(echo "$TAG" | sed 's/-luna$//')  # Rimuove "-luna"
-    - docker build -t $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED -t $GITLAB_REGISTRY_IMAGE:latest -t $AWS_REGISTRY_IMAGE:$TAG_CLEANED -t $AWS_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
-    - docker push $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED
-    - docker push $GITLAB_REGISTRY_IMAGE:latest
-    - docker push $AWS_REGISTRY_IMAGE:$TAG_CLEANED
-    - docker push $AWS_REGISTRY_IMAGE:latest
+    - |
+      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
+      TAG_CLEANED=$(echo "$TAG" | sed 's/-luna$//')
+      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED -t $GITLAB_REGISTRY_IMAGE:latest -t $AWS_REGISTRY_IMAGE:$TAG_CLEANED -t $AWS_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
+      docker push $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED
+      docker push $GITLAB_REGISTRY_IMAGE:latest
+      docker push $AWS_REGISTRY_IMAGE:$TAG_CLEANED
+      docker push $AWS_REGISTRY_IMAGE:latest
 
 build-develop:
   variables:
@@ -38,10 +39,11 @@ build-develop:
   only:
     - develop
   script:
-    - if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
-    - docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
-    - docker push $GITLAB_REGISTRY_IMAGE:$TAG
-    - docker push $GITLAB_REGISTRY_IMAGE:latest
+    - |
+      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
+      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
+      docker push $GITLAB_REGISTRY_IMAGE:$TAG
+      docker push $GITLAB_REGISTRY_IMAGE:latest
 
 release:
   variables:
@@ -52,15 +54,16 @@ release:
     - build-main
   image: curlimages/curl:latest
   script:
-    - TAG_CLEANED=$(echo "$CI_COMMIT_TAG" | sed 's/-luna$//')
-    - echo "Creating GitLab Release for tag: $TAG_CLEANED"
-    - echo "Docker Image AWS" > docker-info.txt
-    - echo "  Registry: $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
-    - echo "  Pull Command: docker pull $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
-    - echo "" >> docker-info.txt
-    - echo "Docker Image GitLab" >> docker-info.txt
-    - echo "  Registry: $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
-    - echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
+    - |
+      TAG_CLEANED=$(echo "$CI_COMMIT_TAG" | sed 's/-luna$//')
+      echo "Creating GitLab Release for tag: $TAG_CLEANED"
+      echo "Docker Image AWS" > docker-info.txt
+      echo "  Registry: $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
+      echo "  Pull Command: docker pull $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
+      echo "" >> docker-info.txt
+      echo "Docker Image GitLab" >> docker-info.txt
+      echo "  Registry: $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
+      echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> docker-info.txt
     - |
       curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
       --data "name=Release $TAG_CLEANED" \
