fix(luna): gitlab ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -35,6 +35,19 @@ prebuild:
     reports:
       dotenv: variables.env
 
+build-develop:
+  variables:
+    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
+  stage: build
+  only:
+    - develop
+  script:
+    - |
+      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
+      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
+      docker push $GITLAB_REGISTRY_IMAGE:$TAG
+      docker push $GITLAB_REGISTRY_IMAGE:latest
+
 build-main:
   stage: build
   rules:
@@ -54,19 +67,11 @@ build-main:
       docker push $GITLAB_REGISTRY_IMAGE:latest
       docker push $AWS_REGISTRY_IMAGE:$VERSION
       docker push $AWS_REGISTRY_IMAGE:latest
-
-build-develop:
-  variables:
-    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
-  stage: build
-  only:
-    - develop
-  script:
-    - |
-      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
-      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
-      docker push $GITLAB_REGISTRY_IMAGE:$TAG
-      docker push $GITLAB_REGISTRY_IMAGE:latest
+    - echo "TAG=${TAG}" >> variables.env
+    - echo "VERSION=${VERSION}" >> variables.env
+  artifacts:
+    reports:
+      dotenv: variables.env
 
 prepare:
   stage: prepare
@@ -95,9 +100,13 @@ prepare:
       echo "Docker Image GitLab" >> RELEASE_DESCRIPTION.txt
       echo "  Registry: $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
       echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
+    - echo "TAG=${TAG}" >> variables.env
+    - echo "VERSION=${VERSION}" >> variables.env
   artifacts:
     paths:
       - RELEASE_DESCRIPTION.txt
+    reports:
+      dotenv: variables.env
 
 release:
   stage: release
@@ -111,7 +120,8 @@ release:
     - if: $CI_COMMIT_TAG == null
       when: never
   needs:
-    - prepare
+    - job: prepare
+      artifacts: true
   script:
     - echo "Running release-job for $TAG"
   release:
