fix(luna): gitlab ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,4 @@
 variables:
-  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
   AWS_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
   AWS_REGISTRY_IMAGE: $AWS_REGISTRY/globaleaks
   GITLAB_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
@@ -13,24 +12,47 @@ default:
     - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY
 
 stages:
+  - prebuild
   - build
   - prepare
   - release
 
-build-main:
-  variables:
-    TAG: $CI_COMMIT_TAG
-  stage: build
-  only:
-    - tags
+prebuild:
+  stage: prebuild
+  rules:
+    - if: $CI_COMMIT_TAG != null
+      when: always
+    - if: $CI_COMMIT_TAG == null
+      when: never
   script:
     - |
-      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
-      TAG_CLEANED=$(echo "$TAG" | sed 's/-luna$//')
-      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED -t $GITLAB_REGISTRY_IMAGE:latest -t $AWS_REGISTRY_IMAGE:$TAG_CLEANED -t $AWS_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
-      docker push $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED
+      if [ -z "$CI_COMMIT_TAG" ]; then echo "❌ ERROR: CI_COMMIT_TAG is not set!"; exit 1; fi
+      TAG=$(echo "$CI_COMMIT_TAG" | sed 's/-luna$//')
+      VERSION="${TAG#v}"
+    - echo "TAG=${TAG}" >> variables.env
+    - echo "VERSION=${VERSION}" >> variables.env
+  artifacts:
+    reports:
+      dotenv: variables.env
+
+build-main:
+  stage: build
+  rules:
+    - if: $CI_COMMIT_TAG != null
+      when: always
+    - if: $CI_COMMIT_TAG == null
+      when: never
+  script:
+    - |
+      docker build \
+      -t $GITLAB_REGISTRY_IMAGE:$VERSION \
+      -t $GITLAB_REGISTRY_IMAGE:latest \
+      -t $AWS_REGISTRY_IMAGE:$VERSION \
+      -t $AWS_REGISTRY_IMAGE:latest \
+      . -f docker/Dockerfile.deploy
+      docker push $GITLAB_REGISTRY_IMAGE:$VERSION
       docker push $GITLAB_REGISTRY_IMAGE:latest
-      docker push $AWS_REGISTRY_IMAGE:$TAG_CLEANED
+      docker push $AWS_REGISTRY_IMAGE:$VERSION
       docker push $AWS_REGISTRY_IMAGE:latest
 
 build-develop:
@@ -48,8 +70,6 @@ build-develop:
 
 prepare:
   stage: prepare
-  variables:
-    TAG: $CI_COMMIT_TAG
   needs:
     - build-main
   rules:
@@ -60,10 +80,7 @@ prepare:
   before_script: []
   script:
     - |
-      TAG_CLEANED=$(echo "$TAG" | sed 's/-luna$//')
-      echo "TAG_CLEANED=${TAG_CLEANED}" >> variables.env
-      echo "Preparing GitLab Release for tag: $TAG_CLEANED"
-      VERSION="${TAG_CLEANED#v}"
+      echo "Preparing GitLab Release for tag: $TAG"
       awk -v version="Changes in version $VERSION" '
           $0 ~ version {flag=1; print; next}
           flag && /^[[:space:]]*$/ {exit}
@@ -72,25 +89,22 @@ prepare:
       echo ""
       echo ""
       echo "Docker Image AWS" >> RELEASE_DESCRIPTION.txt
-      echo "  Registry: $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> RELEASE_DESCRIPTION.txt
-      echo "  Pull Command: docker pull $AWS_REGISTRY_IMAGE:$TAG_CLEANED" >> RELEASE_DESCRIPTION.txt
+      echo "  Registry: $AWS_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
+      echo "  Pull Command: docker pull $AWS_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
       echo "" >> RELEASE_DESCRIPTION.txt
       echo "Docker Image GitLab" >> RELEASE_DESCRIPTION.txt
-      echo "  Registry: $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> RELEASE_DESCRIPTION.txt
-      echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$TAG_CLEANED" >> RELEASE_DESCRIPTION.txt
-      RELEASE_DESCRIPTION="$(cat RELEASE_DESCRIPTION.txt)"
-      echo "RELEASE_DESCRIPTION=${RELEASE_DESCRIPTION}" >> variables.env
+      echo "  Registry: $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
+      echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
   artifacts:
-    reports:
-      dotenv: variables.env
+    paths:
+      - RELEASE_DESCRIPTION.txt
 
 release:
   stage: release
   image: registry.gitlab.com/gitlab-org/release-cli:latest
-  variables:
-    TAG: $CI_COMMIT_TAG
   services: []
-  before_script: []
+  before_script:
+    - RELEASE_DESCRIPTION="$(cat RELEASE_DESCRIPTION.txt)"
   rules:
     - if: $CI_COMMIT_TAG != null
       when: always
@@ -101,7 +115,7 @@ release:
   script:
     - echo "Running release-job for $TAG"
   release:
-    name: 'Release $TAG_CLEANED'
-    description: '$RELEASE_CHANGELOG'
-    tag_name: '$TAG_CLEANED'
-    ref: '$TAG'
+    name: 'Release v$TAG'
+    description: '$RELEASE_DESCRIPTION'
+    tag_name: 'v$TAG'
+    ref: '$CI_COMMIT_TAG'
